name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: action/checkout@v3
    - name: Set up JDK 1.8.0_192
      uses: actions/setup-java@v3
      with:
        java-version: '1.8.0_192'
        
    - name: Build
      run: ant - buildfile build.xml
